DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'ehr') THEN
        CREATE SCHEMA ehr;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS ehr.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'ehr') THEN
        CREATE SCHEMA ehr;
    END IF;
END $EF$;

CREATE TABLE ehr.data_protection_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendly_name text,
    xml text,
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

CREATE TABLE ehr.quick_texts (
    id uuid NOT NULL,
    shortcut character varying(32) NOT NULL,
    body character varying(4000) NOT NULL,
    version integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_quick_texts PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_quick_texts_shortcut ON ehr.quick_texts (shortcut);

INSERT INTO ehr.__ef_migrations_history (migration_id, product_version)
VALUES ('20261001063107_InitialQuickText', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE ehr.change_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_id xid8 NOT NULL DEFAULT (pg_current_xact_id()),
    table_name character varying(63) NOT NULL,
    row_id uuid NOT NULL,
    CONSTRAINT pk_change_log PRIMARY KEY (id)
);

CREATE TABLE ehr.sync_operations (
    idempotency_key uuid NOT NULL,
    row_id uuid NOT NULL,
    applied_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_sync_operations PRIMARY KEY (idempotency_key)
);

CREATE INDEX ix_change_log_transaction_id ON ehr.change_log (transaction_id);

INSERT INTO ehr.__ef_migrations_history (migration_id, product_version)
VALUES ('20261007041719_SyncLog', '10.0.12');

COMMIT;

