namespace Ehr.Data;

// A shared phrase that clinicians expand by typing its shortcut, such as ".nad" for "No acute distress."
// The walking skeleton's feature: not PHI, editable, and synced to the desktop app.
public class QuickText
{
    // UUIDv7, generated by whoever creates the row: the web app, or the desktop app while offline.
    public Guid Id { get; set; }

    public required string Shortcut { get; set; }

    public required string Body { get; set; }

    // Goes up by one on every update. A save that started from an older version is a conflict.
    public int Version { get; set; } = 1;

    public DateTimeOffset UpdatedAt { get; set; }
}
